name: "CI Pipeline"

# This workflow will run on every push to any branch.
on:
  push:

jobs:
  # We define a single job named 'build-and-test'.
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the code
      # This uses the official 'checkout' Action.
      - name: "Checkout code"
        uses: actions/checkout@v3

      # Step 2: Set up Python
      # This uses the official 'setup-python' Action.
      # The 'with' block provides parameters to the Action.
      - name: "Set up Python 3.9"
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      # Step 3: Install dependencies
      # We use 'run' for this, as it's a simple shell command.
      - name: "Install dependencies"
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      
      # Step 4: Run tests
      # We run the 'pytest' command, which will automatically discover
      # and run the tests in 'test_app.py'.
      - name: "Run tests with pytest"
        run: pytest
